<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [

            // ── Software Development ────────────────────────────────────────

            [
                'name'             => 'INDIPRO TELKOM SURABAYA',
                'slug'             => 'indipro-telkom-surabaya',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About UNDIPRO - Online Booking System',
                'hero_description' => 'PT Telkom Indonesia (Persero) Tbk (Telkom) is the largest state-owned enterprise in Indonesia, operating in information and communication technology (ICT) services and telecommunications networks.',
                'description'      => 'This online booking platform is designed for Telkom Surabaya to simplify and streamline the process of scheduling home internet installations. The system provides a seamless digital experience, allowing users to book installation services easily and efficiently through a single integrated platform.\nEquipped with advanced GIS-based coverage mapping, the platform enables users to check service availability based on their location, ensuring accurate and reliable booking processes. This integration helps both customers and service providers optimize scheduling and coverage planning.\nThrough this implementation, Telkom Surabaya can enhance service accessibility, improve operational efficiency, and deliver a more convenient and modern booking experience for customers.',
                'image'            => 'projects/indipro-telkom-surabaya.jpg',
                'images'           => ['projects/indipro-telkom-surabaya.jpg'],
            ],
            [
                'name'             => 'AEGIS - SISTEM AKADEMIK',
                'slug'             => 'aegis-sistem-akademik',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About AEGIS - Academic System',
                'hero_description' => 'Airlangga University (UNAIR) is a leading state university in Surabaya, East Java. As one of Indonesia’s oldest and most prestigious institutions, it is well known for excellence in health sciences, medicine, veterinary medicine, and social and political sciences.',
                'description'      => 'This academic system application is designed to support and enhance the learning ecosystem of the Faculty of Dentistry, Universitas Airlangga. It provides an integrated platform that streamlines academic processes for both educators and students, ensuring a more efficient and organized workflow.\nThe system enables better management of academic activities, improves accessibility to information, and supports a more effective teaching and learning experience.\nThrough this implementation, the Faculty of Dentistry, Universitas Airlangga can optimize academic operations, improve collaboration between educators and students, and support a more effective and modern learning environment.',
                'image'            => 'projects/aegis-sistem-akademik.jpg',
                'images'           => ['projects/aegis-sistem-akademik.jpg'],
            ],
            [
                'name'             => 'E-SALES ZELLTECH',
                'slug'             => 'e-sales-zelltech',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Sales Tracking & Project Monitoring System',
                'hero_description' => 'Zelltech is a premium brand of roof insulation (heat dampers) and construction materials (sandwich panels) in Indonesia, manufactured by PT Cellcius Indoperkasa.',
                'description'      => 'This application is developed for Zelltech / PT Celcius Indo Perkasa as a powerful solution to support sales tracking and project monitoring within a single integrated platform. The system is designed to help the company manage sales activities and project progress more efficiently and in a structured manner.\nThe platform enables real-time monitoring of sales performance and ongoing projects, providing clear visibility into operational workflows and progress. With a centralized system, teams can collaborate more effectively while ensuring better data accuracy and reporting.\nThrough this implementation, PT Celcius Indo Perkasa can improve operational efficiency, enhance project oversight, and make more informed business decisions based on accurate and up-to-date information.',
                'image'            => 'projects/e-sales-zelltech.jpg',
                'images'           => ['projects/e-sales-zelltech.jpg'],
            ],
            [
                'name'             => 'WAREHOUSE SYSTEM - MJS UNILEVER',
                'slug'             => 'warehouse-system-mjs-unilever',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Warehouse Management System',
                'hero_description' => 'Unilever is one of the world’s largest multinational Fast-Moving Consumer Goods (FMCG) companies, producing food, beverages, cleaning agents, and personal care products, with its brands sold in over 190 countries.',
                'description'      => 'This warehouse management system is developed for MJA Company, a trusted distributor of Unilever products, to streamline inventory tracking and distribution processes within a single integrated platform. The system is designed to support efficient stock management and improve overall warehouse operations.\nThe platform provides real-time visibility of inventory, enabling accurate tracking of stock movement and availability across the distribution process. This helps reduce errors, improve stock control, and ensure smoother coordination between warehouse and distribution activities.\nThrough this implementation, MJA Company can enhance operational efficiency, maintain better inventory accuracy, and optimize distribution performance to support business growth.',
                'image'            => 'projects/warehouse-system-mjs-unilever.jpg',
                'images'           => ['projects/warehouse-system-mjs-unilever.jpg'],
            ],
            [
                'name'             => 'QPS WIKA GEDUNG',
                'slug'             => 'qps-wika-gedung',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Property Assessment System',
                'hero_description' => 'PT Wijaya Karya (Persero) Tbk, commonly known as WIKA, is an Indonesian state-owned enterprise engaged in construction, engineering, procurement, and construction (EPC), as well as investment.',
                'description'      => 'This property assessment application is developed for PT. WIKA Gedung to support the surveying process of residential units at Puncak CBD Apartments. The system is designed to simplify and digitize property assessment activities, making the process more efficient and well-structured.\nThe platform enables field surveyors to collect and manage property data in a more organized and accurate manner. By digitizing the assessment process, the system reduces manual work, minimizes errors, and improves data consistency across projects.\nThrough this implementation, PT. WIKA Gedung can enhance the efficiency of property assessments, improve data accuracy, and support better decision-making in managing residential development projects.',
                'image'            => 'projects/qps-wika-gedung.jpg',
                'images'           => ['projects/qps-wika-gedung.jpg'],
            ],
            [
                'name'             => 'RESCUE.ID',
                'slug'             => 'rescueid',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About RESCUE.ID - Emergency Response System',
                'hero_description' => 'Dr. Soetomo General Hospital is a provincial-owned hospital under the East Java Government, serving as the highest referral (tertiary) and teaching hospital (Class A) in Eastern Indonesia, located in Surabaya. It provides comprehensive subspecialty services, research facilities, and a 24-hour emergency unit.',
                'description'      => 'This application is developed to support emergency response at Dr. Soetomo Hospital, Surabaya, particularly for handling heart attack cases through the Code Blue system. It is designed to provide a faster and more structured approach to emergency reporting and response coordination.\nThe platform enables medical staff to report emergencies quickly while also providing guidance for handling critical situations. This ensures that response teams can act promptly and follow the correct procedures during life-threatening conditions.\nThrough this implementation, the hospital can improve response time, enhance coordination among medical teams, and ensure more effective handling of emergency cases.',
                'image'            => 'projects/rescueid.png',
                'images'           => ['projects/rescueid.png'],
            ],
            [
                'name'             => 'SILY',
                'slug'             => 'sily',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About SILY - Smart City Portal',
                'hero_description' => 'Lamongan is a regency in East Java Province, Indonesia, located along the northern coastal area (Pantura) and part of the Surabaya metropolitan region (Gerbangkertosusila).',
                'description'      => 'This Smart City Portal application is developed for Lamongan District to support digital public services through a single integrated platform. The system is designed to enhance community engagement and improve accessibility to city information and services.\nThe platform features 360-degree photo exploration, allowing users to virtually explore locations across the district. It also provides issue reporting functionality, enabling citizens to report problems directly, as well as emergency response features to ensure faster handling of urgent situations.\nThrough this implementation, Lamongan District can improve public service efficiency, strengthen communication with citizens, and support the development of a more responsive and connected smart city ecosystem.',
                'image'            => 'projects/sily.jpg',
                'images'           => ['projects/sily.jpg'],
            ],
            [
                'name'             => 'TOWER IN YOUR HAND',
                'slug'             => 'tower-in-your-hand',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Tower Supervision System',
                'hero_description' => 'Pamekasan is a regency in East Java Province, Indonesia. It is located on Madura Island, bordered by the Java Sea to the north, the Madura Strait to the south, Sampang Regency to the west, and Sumenep Regency to the east.',
                'description'      => 'This application is developed for the Department of Communication and Information Technology of Pamekasan Regency to support the supervision and management of telecommunication towers. The system is designed to provide a more structured and efficient approach to monitoring tower data and related activities.\nThe platform enables centralized data management, allowing authorities to track tower information, monitor conditions, and ensure compliance with regulations. By digitizing the supervision process, the system improves data accuracy and simplifies reporting and monitoring tasks.\nThrough this implementation, the department can enhance oversight efficiency, improve data management, and support better decision-making in managing telecommunication infrastructure across the region.',
                'image'            => 'projects/tower-in-your-hand.png',
                'images'           => ['projects/tower-in-your-hand.png'],
            ],
            [
                'name'             => 'SIPINTAR',
                'slug'             => 'sipintar',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About SIPINTAR - Spatial Planning Information System',
                'hero_description' => 'Banjarbaru has been the capital of South Kalimantan Province since 2022, replacing Banjarmasin. The city was designed as the new administrative center and is known for its orderly urban planning, the nickname “City of Dreams”, as well as its role as an educational hub and business center.',
                'description'      => 'This spatial planning information system is developed for the Public Works and Housing Department of Banjarbaru City to provide easy access to spatial planning data and information. The system is designed to support more efficient and structured management of regional planning information.\nThe platform enables users to search and explore spatial planning data, helping stakeholders better understand land use, zoning, and development regulations. By digitizing this information, the system improves accessibility, accuracy, and transparency in spatial planning processes.\nThrough this implementation, the department can enhance public service delivery, support better planning decisions, and promote more effective management of urban development.',
                'image'            => 'projects/sipintar.png',
                'images'           => ['projects/sipintar.png'],
            ],
            [
                'name'             => 'BMOMS',
                'slug'             => 'bmoms',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About BMOMS - Maternal Mental Health Screening System',
                'hero_description' => 'Keswa (Mental Health) at Community Health Centers is a primary care service aimed at improving community mental health through promotive, preventive, curative, and rehabilitative approaches.',
                'description'      => 'This application is developed to support maternal care through mental health screening for expectant mothers. The system is designed to provide a more structured and efficient approach to early detection and monitoring of maternal mental health conditions.\nThe platform enables screening results to be recorded centrally at the Health Office (Dinkes), ensuring better data management and accessibility. It also automates the referral process to KIA and mental health (Keswa) services at Puskesmas, allowing faster and more coordinated follow-up care.\nThrough this implementation, healthcare providers can improve early detection, enhance service coordination, and ensure better support for maternal health throughout the pregnancy journey.',
                'image'            => 'projects/bmoms.png',
                'images'           => ['projects/bmoms.png'],
            ],
            [
                'name'             => 'FOUNDATION DONATION PORTAL',
                'slug'             => 'foundation-donation-portal',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Donation Platform',
                'hero_description' => 'Masjid Raudlatul Falah is a religious center in Surabaya, officially inaugurated by the Mayor in August 2011.',
                'description'      => 'This platform is developed to facilitate donations for mosque construction projects under the auspices of the Rodioutl Falah Surabaya foundation. The system is designed to provide a simple, transparent, and accessible way for donors to contribute to ongoing development initiatives.\nThe platform enables users to make donations digitally while ensuring that all contributions are properly recorded and managed. It also helps the foundation monitor fundraising progress and manage project funding more effectively.\nThrough this implementation, the foundation can improve donation management, increase transparency, and expand its reach in supporting mosque construction projects.',
                'image'            => 'projects/foundation-donation-portal.png',
                'images'           => ['projects/foundation-donation-portal.png'],
            ],
            [
                'name'             => 'SIMASTER BKD',
                'slug'             => 'simaster-bkd',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Human Resources Information System',
                'hero_description' => 'The Regional Civil Service Agency (BKD) of East Java Province is a local government body responsible for managing the civil service (Aparatur Sipil Negara) within the East Java Provincial Government.',
                'description'      => 'This human resources information system is developed for the East Java Province in collaboration with the Regional Personnel Agency (Badan Kepegawaian Daerah). The system is designed to integrate multiple personnel databases into a single, unified platform.\nBuilt on a hybrid device environment, the platform enables more flexible access while ensuring centralized and structured data management. It supports efficient handling of employee information, improving data consistency and accessibility across institutions.\nThrough this implementation, the government can enhance administrative efficiency, streamline data integration, and support more accurate decision-making in managing human resources.',
                'image'            => 'projects/simaster-bkd.jpg',
                'images'           => ['projects/simaster-bkd.jpg'],
            ],
            [
                'name'             => 'JOB CENTER BERAU COAL ENERGY',
                'slug'             => 'job-center-berau-coal-energy',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Recruitment & Job Fair System',
                'hero_description' => 'PT Berau Coal is one of Indonesia’s largest and oldest coal mining companies, operating in Berau Regency, East Kalimantan. It is part of the Sinar Mas Group and ranks among Indonesia’s top coal producers, serving both domestic and export markets.',
                'description'      => 'This website and mobile-based information system is developed for Berau Coal Energy to support recruitment processes and job fair activities within a single integrated platform. The system is designed to simplify candidate registration and improve overall recruitment management.\nThe platform enables applicants to register online, track their application progress, and receive updates on their registration status in real time. It also provides features for participating in job fair events, creating a more accessible and organized recruitment experience.\nThrough this implementation, Berau Coal Energy can enhance recruitment efficiency, improve communication with candidates, and streamline the overall hiring process.',
                'image'            => 'projects/job-center-berau-coal-energy.jpg',
                'images'           => ['projects/job-center-berau-coal-energy.jpg'],
            ],
            [
                'name'             => 'E-TRUCKING',
                'slug'             => 'e-trucking',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Truck Monitoring System',
                'hero_description' => 'PT Java Mining Fertilizo (JMF) is a mining and trading company specializing in non-metallic mineral fertilizers. JMF produces and exports dolomite, phosphate, and agricultural limestone to meet industrial and agricultural needs.',
                'description'      => 'This application is developed for PT Javara Multiindo Fertilizo to support the monitoring of mining truck operations through an efficient check-in and check-out system. The system is designed to ensure better control and visibility over vehicle movements.\nThe platform enables drivers and operators to record check-in and check-out activities in a structured and timely manner, allowing real-time tracking of truck operations. This helps improve coordination, reduce manual errors, and ensure accurate operational records.\nThrough this implementation, the company can enhance operational efficiency, improve monitoring accuracy, and support better decision-making in managing mining logistics.',
                'image'            => 'projects/e-trucking.jpg',
                'images'           => ['projects/e-trucking.jpg'],
            ],
            [
                'name'             => 'DIANCA GOODS',
                'slug'             => 'dianca-goods',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About E-Commerce System',
                'hero_description' => 'Dianca Goods is a popular cosmetics and skincare store located in Bengkulu, offering a wide range of beauty products. It is well-known for its aesthetic and comfortable atmosphere.',
                'description'      => 'This user-friendly e-commerce platform is developed to support both customers and dropshippers in managing cosmetic product transactions within a single integrated system. The platform is designed to provide a seamless shopping and selling experience.\nThe system enables users to browse products, place orders, and manage transactions efficiently. It also supports dropshipper activities, allowing partners to participate in the sales process more easily.\nIntegrated with WhatsApp, the platform simplifies user registration and verification processes, ensuring faster onboarding and improved communication between users and the system.\nThrough this implementation, the business can enhance customer experience, streamline sales operations, and expand its distribution network through dropshippers.',
                'image'            => 'projects/dianca-goods.jpg',
                'images'           => ['projects/dianca-goods.jpg'],
            ],
            [
                'name'             => 'PPDB SMPN BENGKULU',
                'slug'             => 'ppdb-smpn-bengkulu',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Student Admission System',
                'hero_description' => 'Bengkulu City is the capital of Bengkulu Province, Indonesia, located on the western coast of Sumatra. Known as the “Land of Rafflesia,” it is home to Fort Marlborough and is the second-largest city on Sumatra’s west coast after Padang.',
                'description'      => 'This application is developed to assist and accommodate the new student admission process for schools in Bengkulu Province. The system is designed to simplify and streamline the registration and selection process through a centralized digital platform.\nThe platform enables prospective students to register online, submit required data, and track their admission status in a structured and transparent manner. It also helps schools manage applicant data more efficiently and ensures a more organized selection process.\nThrough this implementation, the admission process becomes more efficient, transparent, and accessible for both students and educational institutions.',
                'image'            => 'projects/ppdb-smpn-bengkulu.png',
                'images'           => ['projects/ppdb-smpn-bengkulu.png'],
            ],
            [
                'name'             => 'PJB UNITE',
                'slug'             => 'pjb-unite',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Social & Monitoring Platform',
                'hero_description' => 'PT PJB (Pembangkitan Jawa-Bali) has now transformed into PT PLN Nusantara Power (PLN NP), a subholding of PT PLN (Persero) that focuses on the electricity generation business. It is recognized as the largest power generation company in Southeast Asia.',
                'description'      => 'This application is developed for PJB Services to support social interaction, communication, and monitoring activities within a single integrated platform. The system is designed to create a more connected and collaborative digital environment for users.\nThe platform accommodates social media features, group interactions, and real-time chat, enabling users to communicate and collaborate more effectively. It also includes monitoring capabilities to help manage activities and ensure better oversight across the system.\nThrough this implementation, PJB Services can improve internal communication, enhance collaboration, and maintain more structured monitoring of operational activities.',
                'image'            => 'projects/pjb-unite.jpg',
                'images'           => ['projects/pjb-unite.jpg'],
            ],
            [
                'name'             => 'SPATIAL PLANNING MANAGEMENT SYSTEM OF BANJARBARU REGENCY',
                'slug'             => 'spatial-planning-management-system-of-banjarbaru-regency',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Development Permit System',
                'hero_description' => 'Banjarbaru has been the capital of South Kalimantan Province since 2022, replacing Banjarmasin. The city was designed as the new administrative center and is known for its orderly urban planning, the nickname “City of Dreams”, as well as its role as an educational hub and business center.',
                'description'      => 'This application is developed to provide easy access to information related to area classifications and permitted activities within a region. The system is designed to support users in understanding zoning regulations and development guidelines in a structured and accessible way.\nThe platform enables users to search for area information, view types of allowed activities, and submit applications for development permits through a single integrated system. By digitizing these processes, the system improves transparency and simplifies administrative procedures.\nThrough this implementation, the process of accessing spatial information and applying for permits becomes more efficient, accurate, and user-friendly.',
                'image'            => 'projects/spatial-planning-management-system-of-banjarbaru-regency.webp',
                'images'           => ['projects/spatial-planning-management-system-of-banjarbaru-regency.webp'],
            ],
            [
                'name'             => 'DIGITAL ARCHIVE DISDUKCAPIL KAB. LAMONGAN',
                'slug'             => 'digital-archive-disdukcapil-kab-lamongan',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Digital Archive System',
                'hero_description' => 'Lamongan is a regency in East Java Province, Indonesia, located along the northern coastal area (Pantura) and part of the Surabaya metropolitan region (Gerbangkertosusila).',
                'description'      => 'This digital archive system is a web-based application designed to support the digitization and management of documents in a structured and organized manner. The system helps institutions store and access documents more efficiently through a centralized platform.\nThe platform enables documents to be categorized based on specific attributes such as year, name, and national identity number. It also allows administrators to assign labels for better organization and easier retrieval of archived files.\nThrough this implementation, organizations can improve document management, enhance data accessibility, and ensure a more efficient and systematic archiving process.',
                'image'            => 'projects/digital-archive-disdukcapil-kab-lamongan.jpg',
                'images'           => ['projects/digital-archive-disdukcapil-kab-lamongan.jpg'],
            ],
            [
                'name'             => 'COMPANY PROFILE & ORDERING SYSTEM ARCHIRECON',
                'slug'             => 'company-profile-and-ordering-system-archirecon',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Company Profile & Ordering System',
                'hero_description' => 'Archirecon is an architecture consultancy established in Surabaya. Specializing in minimalist residential architecture and interior design, the firm provides free consultation services and caters to clients throughout Indonesia.',
                'description'      => 'This mobile-based application is developed for Archirecon to showcase company profile information and facilitate the ordering of architectural design services within a single integrated platform. The system is designed to provide a more accessible and convenient experience for clients.\nThe platform enables users to explore company information, view design portfolios, and place orders for architectural services directly through the application. By digitizing the ordering process, the system simplifies communication and improves service accessibility.\nThrough this implementation, Archirecon can enhance client engagement, streamline service requests, and provide a more modern and efficient way for customers to access architectural design services.',
                'image'            => 'projects/company-profile-and-ordering-system-archirecon.jpg',
                'images'           => ['projects/company-profile-and-ordering-system-archirecon.jpg'],
            ],
            [
                'name'             => 'DIGITAL FINANCIAL PLATFORM BMT MUDA',
                'slug'             => 'digital-financial-platform-bmt-muda',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Digital Financial Platform',
                'hero_description' => 'BMT MUDA (Baitul Maal Wat Tamwil Mandiri Ukhuwah Persada) is a Sharia cooperative and microfinance institution based in East Java, particularly Surabaya. It focuses on non-usury financing, community economic empowerment, and the management of social funds (ZISWAF). Its motto is “Empowered, Independent, Prosperous.”',
                'description'      => 'This digital financial platform is developed for BMT Muda to support efficient microfinance operations within a single integrated system. The platform is designed to enhance the management of community-based financial services in a more structured and accessible way.\nThe system enables streamlined handling of financial activities, improving data management and operational workflows. It supports better monitoring and management of microfinance services, ensuring more organized and reliable processes.\nThrough this implementation, BMT Muda can improve operational efficiency, strengthen financial service delivery, and support the growth of community-based economic activities.',
                'image'            => 'projects/digital-financial-platform-bmt-muda.jpg',
                'images'           => ['projects/digital-financial-platform-bmt-muda.jpg'],
            ],
            [
                'name'             => 'MINING RAW MATERIAL SUPPLY CHAIN MANAGEMENT SYSTEM',
                'slug'             => 'mining-raw-material-supply-chain-management-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Mining Supply Chain System',
                'hero_description' => null,
                'description'      => 'This Mining Application System (Raw Material Supply Chain) is a web-based platform designed to manage and monitor the flow of raw materials from mining sites in a structured and integrated manner. The system supports better visibility and control over supply chain operations.\nThe platform enables management of raw material data from multiple mines, including tracking quantities and types of materials available at each location. It also provides analysis of raw material stock, helping stakeholders understand availability and distribution more accurately.\nThrough this implementation, companies can improve supply chain efficiency, enhance stock monitoring, and support more informed decision-making in managing mining operations.',
                'image'            => 'projects/mining-raw-material-supply-chain-management-system.jpg',
                'images'           => ['projects/mining-raw-material-supply-chain-management-system.jpg'],
            ],
            [
                'name'             => 'EMPLOYEE PERFORMANCE EVALUATION SYSTEM',
                'slug'             => 'employee-performance-evaluation-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Performance Evaluation System',
                'hero_description' => null,
                'description'      => 'This web-based application is developed to analyze the performance value index of marketing employees in mining companies. The system is designed to provide a structured and objective approach to evaluating employee performance.\nThe platform enables the calculation and monitoring of performance scores for each employee, presenting the results in a clear and organized manner. It also generates promotion recommendations based on individual performance values, helping management make more informed and data-driven decisions.\nThrough this implementation, companies can improve performance evaluation processes, enhance transparency, and support better workforce management.',
                'image'            => 'projects/employee-performance-evaluation-system.jpg',
                'images'           => ['projects/employee-performance-evaluation-system.jpg'],
            ],
            [
                'name'             => 'STATIONERY E-COMMERCE SYSTEM',
                'slug'             => 'stationery-e-commerce-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Online Shop Application',
                'hero_description' => null,
                'description'      => 'This online shop application is developed for Android and iOS platforms to support the digital purchase of office stationery across multiple store outlets. The system is designed to provide a convenient and accessible shopping experience for customers.\nThe platform enables users to browse products, select items from different outlets, and complete transactions directly through the mobile application. It helps streamline the purchasing process while ensuring better accessibility and user experience.\nThrough this implementation, businesses can expand their sales channels, improve customer convenience, and optimize retail operations across outlets.',
                'image'            => 'projects/stationery-e-commerce-system.jpg',
                'images'           => ['projects/stationery-e-commerce-system.jpg'],
            ],
            [
                'name'             => 'LOGISTICS MANAGEMENT SYSTEM',
                'slug'             => 'logistics-management-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Logistics Management System',
                'hero_description' => null,
                'description'      => 'This web-based logistics management system is developed to help users manage transactions and logistics operations within a single integrated platform. The system is designed to simplify and organize various logistics processes more efficiently.\nThe platform enables users to manage and generate important logistics documents such as manifests, invoices, unloading lists, and other related documents in a structured manner. By digitizing these processes, the system improves accuracy, reduces manual work, and ensures better data management.\nThrough this implementation, users can streamline logistics operations, enhance document management, and support more efficient and reliable transaction processes.',
                'image'            => 'projects/logistics-management-system.jpg',
                'images'           => ['projects/logistics-management-system.jpg'],
            ],
            [
                'name'             => 'WAREHOUSE MANAGEMENT SYSTEM',
                'slug'             => 'warehouse-management-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Distribution Center Management System',
                'hero_description' => null,
                'description'      => 'This website and Android-based application system is developed to manage Distribution Center operations within a single integrated platform. The system is designed to support more efficient and structured handling of supply chain activities.\nThe platform enables users to manage purchase orders to suppliers, perform stock forecasting, handle branch deliveries, and record goods receipts at branch locations. By digitizing these processes, the system improves coordination, accuracy, and overall operational control.\nThrough this implementation, companies can streamline distribution workflows, enhance inventory planning, and ensure more efficient management of goods across distribution centers and branches.',
                'image'            => 'projects/warehouse-management-system.jpg',
                'images'           => ['projects/warehouse-management-system.jpg'],
            ],
            [
                'name'             => 'STOCK MANAGEMENT SYSTEM',
                'slug'             => 'stock-management-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Stock Monitoring System',
                'hero_description' => null,
                'description'      => 'This application system is developed across Java desktop, web, and Android platforms to support the monitoring and management of stock across outlets and distribution centers. The system is designed to provide a more integrated and flexible approach to inventory control.\nThe platform enables users to track stock availability, monitor stock movements, and manage inventory data in real time across multiple locations. By centralizing data from different platforms, the system ensures better accuracy and consistency in stock management.\nThrough this implementation, companies can improve inventory visibility, enhance operational coordination, and ensure more efficient stock management across outlets and distribution centers.',
                'image'            => 'projects/stock-management-system.jpg',
                'images'           => ['projects/stock-management-system.jpg'],
            ],
            [
                'name'             => 'ACCOUNTING APPLICATION SYSTEM',
                'slug'             => 'accounting-application-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Accounting System',
                'hero_description' => null,
                'description'      => 'This web-based accounting application is developed to support the generation of financial reports required by accounting staff. The system is designed to simplify and organize accounting processes within a single integrated platform.\nThe platform enables users to manage financial data and generate reports in a structured and accurate manner. By digitizing reporting processes, the system helps reduce manual work and improves data consistency.\nThrough this implementation, companies can enhance reporting efficiency, improve accuracy in financial data, and support better decision-making in accounting operations.',
                'image'            => 'projects/accounting-application-system.jpg',
                'images'           => ['projects/accounting-application-system.jpg'],
            ],
            [
                'name'             => 'POINT OF SALES APPLICATION SYSTEM',
                'slug'             => 'point-of-sales-application-system',
                'category'         => 'software-development',
                'summary_title'    => 'Learning About Point of Sales System',
                'hero_description' => null,
                'description'      => 'This Java desktop-based point of sales application is developed to support sales transactions at each outlet in a structured and reliable manner. The system is designed to ensure smooth transaction processing across retail operations.\nThe platform enables offline transaction capabilities, allowing outlets to continue operating without interruption even when there is no internet connection. Once connectivity is restored, the system automatically synchronizes data with the central database.\nThrough this implementation, businesses can maintain operational continuity, ensure accurate transaction records, and improve overall efficiency in managing sales activities across outlets.',
                'image'            => 'projects/point-of-sales-application-system.jpg',
                'images'           => ['projects/point-of-sales-application-system.jpg'],
            ],

            // ── Digital Branding ────────────────────────────────────────────

            [
                'name'             => 'PROMOTION VIDEO OF MANUFACTURING ENGINEERING UNIVERSITY OF SURABAYA',
                'slug'             => 'promotion-video-of-manufacturing-engineering-university-of-surabaya',
                'category'         => 'digital-branding',
                'summary_title'    => 'Learning About Promotional Video',
                'hero_description' => 'Universitas Surabaya (Ubaya) is a leading private university located in Surabaya, East Java. Renowned for its excellence in education, research, and innovation, Ubaya has established itself as one of Indonesia’s top universities.',
                'description'      => 'This promotional video is developed to showcase the Manufacturing Engineering program at the University of Surabaya. It is designed to present the program in a compelling and informative way to attract prospective students.\nThe video highlights the program’s unique features, facilities, and academic offerings, providing a clear overview of what students can expect. Through engaging visuals and storytelling, it delivers key information in a more appealing and accessible format.\nThrough this implementation, the university can enhance its promotional efforts, strengthen its branding, and effectively communicate the value of its Manufacturing Engineering program to a wider audience.',
                'image'            => 'projects/promotion-video-of-manufacturing-engineering-university-of-surabaya.jpg',
                'images'           => ['projects/promotion-video-of-manufacturing-engineering-university-of-surabaya.jpg'],
            ],
            [
                'name'             => 'REBRANDING DIGITAL MARKETING QUEEN AISYAH SALON & SPA',
                'slug'             => 'rebranding-digital-marketing-queen-aisyah-salon-and-spa',
                'category'         => 'digital-branding',
                'summary_title'    => 'Learning About Digital Rebranding',
                'hero_description' => 'Queen Aisyah Salon & Spa is a women-only beauty and relaxation center located in Sidoarjo. The salon offers a wide range of body and hair treatments, including massage, scrubs, masks, sauna, and nail care, providing a serene and exclusive experience for women.',
                'description'      => 'This digital rebranding initiative is developed for Queen Aisya Salon and SPA to revitalize its brand identity and strengthen its digital marketing presence. The project is designed to create a more modern, consistent, and appealing brand image.\nThe initiative focuses on improving visual identity, refining brand communication, and enhancing digital touchpoints to better engage with customers. By aligning branding elements with current market trends, the rebranding effort ensures a more professional and competitive positioning.\nThrough this implementation, Queen Aisya Salon and SPA can enhance brand recognition, improve customer engagement, and strengthen its overall digital presence.',
                'image'            => 'projects/rebranding-digital-marketing-queen-aisyah-salon-and-spa.png',
                'images'           => ['projects/rebranding-digital-marketing-queen-aisyah-salon-and-spa.png'],
            ],
            [
                'name'             => 'AERIAL VIDEO COMPANY PROFILE PT JMF',
                'slug'             => 'aerial-video-company-profile-pt-jmf',
                'category'         => 'digital-branding',
                'summary_title'    => 'Learning About Company Profile Video',
                'hero_description' => 'PT Java Mining Fertilizo (JMF) is a mining and trading company specializing in non-metallic mineral fertilizers. JMF produces and exports dolomite, phosphate, and agricultural limestone to meet industrial and agricultural needs.',
                'description'      => 'This company profile video is developed for PT Java Mining Fertilizo to present its expertise and services through an engaging aerial perspective. The project is designed to deliver a strong visual representation of the company’s operations and capabilities.\nThe video showcases key activities, facilities, and services using aerial footage, providing a more dynamic and comprehensive view of the company. Through cinematic visuals and storytelling, it communicates the company’s value in a compelling and professional way.\nThrough this implementation, PT Java Mining Fertilizo can strengthen its brand image, enhance corporate presentation, and effectively communicate its capabilities to a wider audience.',
                'image'            => 'projects/aerial-video-company-profile-pt-jmf.png',
                'images'           => ['projects/aerial-video-company-profile-pt-jmf.png'],
            ],

            // ── Startup Incubator ───────────────────────────────────────────

            [
                'name'             => 'HOSPITAL MANAGEMENT INFORMATION SYSTEM – MEDIFY',
                'slug'             => 'hospital-management-information-system-medify',
                'category'         => 'startup-incubator',
                'summary_title'    => 'Learning About Startup Incubation Program',
                'hero_description' => null,
                'description'      => 'This digital startup incubation program is designed to guide and support small startups in their development journey, with a focus on hospital management systems. The program aims to provide structured assistance to help startups grow in a more sustainable and scalable way.\nThe platform offers guidance in key areas such as investment readiness, commercial strategy, and managed services, ensuring startups are equipped with the necessary knowledge and resources. It helps participants develop their products, refine their business models, and improve operational capabilities.\nThrough this implementation, startups can accelerate their growth, strengthen their business foundation, and better prepare to compete in the healthcare technology industry.',
                'image'            => null,
                'images'           => null,
            ],
            [
                'name'             => 'COMMUNITY SPACE SYSTEM – RUANGTEMU',
                'slug'             => 'community-space-system-ruangtemu',
                'category'         => 'startup-incubator',
                'summary_title'    => 'Learning About Startup Incubation Platform',
                'hero_description' => null,
                'description'      => 'This digital-based startup incubation platform is developed to provide information about community events while also accommodating event management activities within a single integrated system. The platform is designed to support the growth of technology-focused communities.\nIt enables users to access updates on events, manage event activities, and engage with programs related to tech investment and tech consulting. By centralizing these functions, the platform creates a more organized and accessible ecosystem for participants and organizers.\nThrough this implementation, the platform can strengthen community engagement, streamline event management processes, and support the development of startups in the technology sector.',
                'image'            => 'projects/community-space-system-ruangtemu.png',
                'images'           => ['projects/community-space-system-ruangtemu.png'],
            ],
            [
                'name'             => 'CONTRACTOR APPLICATION SYSTEM (CONSTRUCTION PROJECT MANAGEMENT AND MONITORING)',
                'slug'             => 'contractor-application-system-construction-project-management-and-monitoring',
                'category'         => 'startup-incubator',
                'summary_title'    => 'Learning About Startup Incubation Platform',
                'hero_description' => null,
                'description'      => 'This digital-based startup incubation platform is developed to support the creation of a project monitoring application system for construction contractors. The program focuses on providing structured guidance and solutions within the areas of tech consulting, commercial strategy, and managed services.\nThe platform enables the development of systems that help contractors monitor project progress, manage workflows, and improve operational visibility. It also supports startups in refining their products and aligning them with industry needs.\nThrough this implementation, startups can accelerate product development, enhance their service offerings, and deliver more effective solutions for the construction industry.',
                'image'            => 'projects/contractor-application-system-construction-project-management-and-monitoring.jpg',
                'images'           => ['projects/contractor-application-system-construction-project-management-and-monitoring.jpg'],
            ],
            [
                'name'             => 'INDUSTRIAL MANUFACTURING APPLICATION SYSTEM',
                'slug'             => 'industrial-manufacturing-application-system',
                'category'         => 'startup-incubator',
                'summary_title'    => 'Learning About Startup Incubation Platform',
                'hero_description' => null,
                'description'      => 'This digital-based startup incubation platform is designed to support the development of manufacturing application systems for industrial use. The program focuses on providing structured guidance through tech consulting and managed services to help startups build scalable and industry-ready solutions.\nThe platform enables the development of systems that support manufacturing processes, improve operational efficiency, and enhance production management. It also assists startups in aligning their products with industry requirements and best practices.\nThrough this implementation, startups can accelerate innovation, strengthen their technical capabilities, and deliver more effective solutions for the manufacturing industry.',
                'image'            => 'projects/industrial-manufacturing-application-system.jpg',
                'images'           => ['projects/industrial-manufacturing-application-system.jpg'],
            ],
            [
                'name'             => 'COOPERATIVE SYSTEM – CALCIUS',
                'slug'             => 'cooperative-system-calcius',
                'category'         => 'startup-incubator',
                'summary_title'    => 'Learning About Startup Incubation Platform',
                'hero_description' => null,
                'description'      => 'This digital-based startup incubation platform is designed to support the development of cooperative organization information systems. The program focuses on providing guidance in tech investment and business consulting to help startups build sustainable and scalable solutions.\nThe platform enables the creation of systems that support cooperative management, improve operational efficiency, and enhance organizational transparency. It also assists startups in refining their business strategies and aligning their solutions with market needs.\nThrough this implementation, startups can strengthen their business foundation, accelerate growth, and deliver effective digital solutions for cooperative organizations.',
                'image'            => 'projects/cooperative-system-calcius.jpg',
                'images'           => ['projects/cooperative-system-calcius.jpg'],
            ],

            // ── IT Consultant ───────────────────────────────────────────────

            [
                'name'             => 'BUILDING MAPPING SYSTEM PLANNING',
                'slug'             => 'building-mapping-system-planning',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About Building Mapping System Planning',
                'hero_description' => 'PT Telkom Indonesia (Persero) Tbk (Telkom) is the largest state-owned enterprise in Indonesia, operating in information and communication technology (ICT) services and telecommunications networks.',
                'description'      => 'This project focuses on planning the implementation of a building mapping system using digital imagery in collaboration with Telkom Indonesia for the Lamongan district government. The system is designed to support accurate documentation of buildings in a structured and efficient manner.\nThe platform utilizes digital mapping technology to capture and organize building data, enabling better visibility of physical assets across the region. This information can be used to support renovation, maintenance planning, and other infrastructure-related needs.\nThrough this implementation, the government can improve data accuracy, enhance planning processes, and support more effective management of regional infrastructure.',
                'image'            => 'projects/building-mapping-system-planning.png',
                'images'           => ['projects/building-mapping-system-planning.png'],
            ],
            [
                'name'             => 'LIVESTOCK MONITORING SYSTEM PLANNING',
                'slug'             => 'livestock-monitoring-system-planning',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About Livestock Monitoring System Planning',
                'hero_description' => 'PT Telkom Indonesia (Persero) Tbk (Telkom) is the largest state-owned enterprise in Indonesia, operating in information and communication technology (ICT) services and telecommunications networks.',
                'description'      => 'This project focuses on planning the implementation of a livestock monitoring system in collaboration with Telkom Indonesia for the Lamongan district government. The system is designed to support real-time monitoring of livestock conditions and behavior through a structured digital approach.\nThe platform enables the tracking of livestock activities and health indicators, providing accurate and timely data for better management. By utilizing monitoring technology, the system helps identify potential health or behavioral issues at an early stage.\nThrough this implementation, the government can improve livestock welfare, enhance operational efficiency, and support more effective management of livestock resources.',
                'image'            => 'projects/livestock-monitoring-system-planning.png',
                'images'           => ['projects/livestock-monitoring-system-planning.png'],
            ],
            [
                'name'             => 'SCHOOL SYSTEM PLANNING',
                'slug'             => 'school-system-planning',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About School System Planning',
                'hero_description' => 'PT Telkom Indonesia (Persero) Tbk (Telkom) is the largest state-owned enterprise in Indonesia, operating in information and communication technology (ICT) services and telecommunications networks.',
                'description'      => 'This project focuses on planning the development of application systems for schools in collaboration with Telkom Indonesia for the Lamongan district government. The activity is carried out as part of IT consulting services, covering requirement analysis and system design.\nThe platform is designed to support school operations by identifying system needs and structuring digital solutions that improve administrative and academic processes. It provides a clear foundation for developing applications that enhance efficiency and support better learning environments.\nThrough this implementation, schools can streamline operations, improve system readiness, and support more effective and organized educational processes.',
                'image'            => 'projects/school-system-planning.png',
                'images'           => ['projects/school-system-planning.png'],
            ],
            [
                'name'             => 'ANALYSIS OF DEVELOPMENT AND NEEDS OF KOPERASI KANA',
                'slug'             => 'analysis-of-development-and-needs-of-koperasi-kana',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About System Analysis & Development',
                'hero_description' => 'Kana Consumer Cooperative is a Surabaya-based cooperative, focused on the export and distribution of sugar, edible bird’s nest, and the development of food and beverage products. The cooperative is renowned for its “Sweet Cooperative” (consignment) program and rapid growth.',
                'description'      => 'This project focuses on the analysis and development of application systems for Koperasi Kana as part of IT consulting services. The process includes planning, system design, and development to ensure the solutions align with user needs and business objectives.\nThe project involves collaboration across multidisciplinary teams, including system analysts, UI/UX designers, as well as security and database experts. This approach ensures that the system is designed with a strong foundation in usability, performance, and security.\nThrough this implementation, Koperasi Kana can develop more effective and reliable systems, improve operational processes, and ensure that technology solutions are aligned with organizational requirements.',
                'image'            => 'projects/analysis-of-development-and-needs-of-koperasi-kana.jpg',
                'images'           => ['projects/analysis-of-development-and-needs-of-koperasi-kana.jpg'],
            ],
            [
                'name'             => 'PLANNING AND DEVELOPMENT OF NEW STUDENT ADMISSION SYSTEM (PPDB)',
                'slug'             => 'planning-and-development-of-new-student-admission-system-ppdb',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About Student Admission System (PPDB)',
                'hero_description' => 'Institut Teknologi Sepuluh Nopember (ITS) is a leading public university in Surabaya, East Java, specializing in science and technology, and widely recognized for its innovations in robotics and automotive engineering. It consistently ranks among the top universities in Indonesia.',
                'description'      => 'This project focuses on planning and developing a New Student Admission System (PPDB) as part of IT consulting services. The system is designed as an online platform to manage the entire admission process in a more efficient and transparent way.\nThe platform enables student registration, data verification, selection processes, and announcement of results within a single integrated system. This project is developed in collaboration with the Sepuluh Nopember Institute of Technology to ensure a well-structured and reliable implementation.\nThrough this implementation, schools can streamline admission processes, improve transparency, and ensure a more organized and efficient system for managing student enrollment.',
                'image'            => 'projects/planning-and-development-of-new-student-admission-system-ppdb.jpg',
                'images'           => ['projects/planning-and-development-of-new-student-admission-system-ppdb.jpg'],
            ],
            [
                'name'             => 'ANALYSIS OF DEVELOPMENT AND NEEDS OF BMT MUDA COOPERATIVE',
                'slug'             => 'analysis-of-development-and-needs-of-bmt-muda-cooperative',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About System Analysis & Development',
                'hero_description' => 'BMT MUDA (Baitul Maal Wat Tamwil Mandiri Ukhuwah Persada) is a Sharia cooperative and microfinance institution based in East Java, particularly Surabaya. It focuses on non-usury financing, community economic empowerment, and the management of social funds (ZISWAF). Its motto is “Empowered, Independent, Prosperous.”',
                'description'      => 'This project focuses on the analysis and development of application systems for Koperasi BMT Muda as part of IT consulting services. The process includes system planning and design to ensure the solutions meet user needs and business requirements.\nThe project involves collaboration with multidisciplinary teams, including system analysts, UI/UX designers, and experts in security and database management. This approach ensures the system is well-designed, secure, and aligned with operational needs.\nThrough this implementation, Koperasi BMT Muda can develop more effective systems, improve operational processes, and ensure better alignment between technology and business goals.',
                'image'            => 'projects/analysis-of-development-and-needs-of-bmt-muda-cooperative.jpg',
                'images'           => ['projects/analysis-of-development-and-needs-of-bmt-muda-cooperative.jpg'],
            ],
            [
                'name'             => 'POC AND PLANNING OF JOB CENTER SYSTEM DEVELOPMENT – BERAU COAL',
                'slug'             => 'poc-and-planning-of-job-center-system-development-berau-coal',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About Job Center System (POC)',
                'hero_description' => 'PT Berau Coal is one of Indonesia’s largest and oldest coal mining companies, operating in Berau Regency, East Kalimantan. It is part of the Sinar Mas Group and ranks among Indonesia’s top coal producers, serving both domestic and export markets.',
                'description'      => 'This project focuses on the development of a Proof of Concept (POC) for a Job Center application system for Berau Coal. The purpose of the POC is to validate and demonstrate that the proposed system design can be effectively implemented.\nThe platform is developed as a prototype to simulate core functionalities and evaluate system feasibility before full-scale development. This helps ensure that the concept aligns with business needs and technical requirements.\nThrough this implementation, the company can reduce development risks, validate system concepts early, and ensure a more efficient transition to full system development.',
                'image'            => 'projects/poc-and-planning-of-job-center-system-development-berau-coal.jpg',
                'images'           => ['projects/poc-and-planning-of-job-center-system-development-berau-coal.jpg'],
            ],
            [
                'name'             => 'POC AND PLANNING OF REGULATORY COMPLIANCE SYSTEM DEVELOPMENT – BERAU COAL',
                'slug'             => 'poc-and-planning-of-regulatory-compliance-system-development-berau-coal',
                'category'         => 'it-consultant',
                'summary_title'    => 'Learning About Regulatory Compliance System (POC)',
                'hero_description' => 'PT Berau Coal is one of Indonesia’s largest and oldest coal mining companies, operating in Berau Regency, East Kalimantan. It is part of the Sinar Mas Group and ranks among Indonesia’s top coal producers, serving both domestic and export markets.',
                'description'      => 'This project focuses on the development of a Proof of Concept (POC) for a Regulatory Compliance System for Berau Coal. The POC is designed to replicate and validate the feasibility of the proposed system concept.\nThe platform is built as a prototype to test key features and ensure that the system design can be implemented effectively. It allows stakeholders to evaluate workflows, compliance processes, and overall system structure before full deployment.\nThrough this implementation, the company can ensure system readiness, minimize risks, and support a more structured approach to developing a regulatory compliance solution.',
                'image'            => 'projects/poc-and-planning-of-regulatory-compliance-system-development-berau-coal.jpg',
                'images'           => ['projects/poc-and-planning-of-regulatory-compliance-system-development-berau-coal.jpg'],
            ],

        ];

        foreach ($projects as $data) {
            Project::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
