<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [

            // ── Software Development ─────────────────────────────────────────

            [
                'name'             => 'Berau Coal ERP',
                'slug'             => 'berau-coal-erp',
                'category'         => 'software-development',
                'description'      => 'Enterprise Resource Planning system for coal mining operations.',
                'hero_description' => 'A comprehensive ERP system designed to manage all aspects of coal mining operations, from resource tracking to logistics and financial management.',
                'summary_title'    => 'Learning About Berau Coal ERP',
                'image'            => 'projects/proyek_all_beraucoal.jpg',
                'images'           => ['projects/proyek_all_beraucoal.jpg'],
            ],
            [
                'name'             => 'BMT Muda',
                'slug'             => 'bmt-muda',
                'category'         => 'software-development',
                'description'      => 'Digital financial platform for microfinance institution.',
                'hero_description' => 'A modern digital financial platform built for BMT Muda, enabling efficient microfinance operations and empowering community-based financial services.',
                'summary_title'    => 'Learning About BMT Muda',
                'image'            => 'projects/proyek_all_bmt.jpg',
                'images'           => ['projects/proyek_all_bmt.jpg'],
            ],
            [
                'name'             => 'WIKA Construction',
                'slug'             => 'wika-construction',
                'category'         => 'software-development',
                'description'      => 'Digital transformation project for state-owned construction company.',
                'hero_description' => 'A digital transformation initiative for WIKA, one of Indonesia\'s largest state-owned construction companies, modernizing project management and operations.',
                'summary_title'    => 'Learning About WIKA Construction',
                'image'            => 'projects/proyek_all_wika.png',
                'images'           => ['projects/proyek_all_wika.png'],
            ],
            [
                'name'             => 'Unilever Analytics',
                'slug'             => 'unilever-analytics',
                'category'         => 'software-development',
                'description'      => 'Business intelligence and analytics platform for FMCG operations.',
                'hero_description' => 'Advanced business intelligence and analytics platform developed for Unilever, enabling data-driven decision making across FMCG operations.',
                'summary_title'    => 'Learning About Unilever Analytics',
                'image'            => 'projects/proyek_all_unilever.png',
                'images'           => ['projects/proyek_all_unilever.png'],
            ],
            [
                'name'             => 'Pamekasan Smart City',
                'slug'             => 'pamekasan-smart-city',
                'category'         => 'software-development',
                'description'      => 'Smart city application for Kabupaten Pamekasan.',
                'hero_description' => 'A smart city application developed for Kabupaten Pamekasan, integrating public services, data analytics, and citizen engagement into a unified digital platform.',
                'summary_title'    => 'Learning About Pamekasan Smart City',
                'image'            => 'projects/proyek_all_pamekasan.png',
                'images'           => ['projects/proyek_all_pamekasan.png'],
            ],
            [
                'name'             => 'INDIPRO TELKOM SURABAYA',
                'slug'             => 'indipro-telkom-surabaya',
                'category'         => 'software-development',
                'description'      => 'Effortless online booking experience for home internet installation, enriched with advanced GIS features.',
                'hero_description' => 'An online booking platform for Telkom Surabaya, enabling seamless home internet installation scheduling with advanced GIS-based coverage mapping.',
                'summary_title'    => 'Learning About INDIPRO Telkom Surabaya',
                'image'            => 'projects/proyek_all_telkom.png',
                'images'           => ['projects/proyek_all_telkom.png'],
            ],
            [
                'name'             => 'E-SALES ZELLTECH',
                'slug'             => 'e-sales-zelltech',
                'category'         => 'software-development',
                'description'      => 'Zelltech\'s application: A powerful tool for PT Celcius Indo Perkasa, enabling seamless sales tracking and project monitoring.',
                'hero_description' => 'A powerful sales tracking and project monitoring application developed for Zelltech / PT Celcius Indo Perkasa.',
                'summary_title'    => 'Learning About E-Sales Zelltech',
                'image'            => 'projects/proyek_all_zelltech.png',
                'images'           => ['projects/proyek_all_zelltech.png'],
            ],
            [
                'name'             => 'SISTEM WAREHOUSE - MJS UNILEVER',
                'slug'             => 'sistem-warehouse-mjs-unilever',
                'category'         => 'software-development',
                'description'      => 'Efficient system facilitating inventory tracking for MJA Company, a trusted Unilever distributor.',
                'hero_description' => 'A warehouse management system built for MJA Company, a trusted Unilever distributor, to streamline inventory tracking and distribution.',
                'summary_title'    => 'Learning About Sistem Warehouse MJS Unilever',
                'image'            => 'projects/proyek_all_unilever.png',
                'images'           => ['projects/proyek_all_unilever.png'],
            ],
            [
                'name'             => 'QPS WIKA GEDUNG',
                'slug'             => 'qps-wika-gedung',
                'category'         => 'software-development',
                'description'      => 'Revolutionizing property assessments, PT. WIKA Gedung employs an innovative application for surveying residential units at Puncak CBD Apartments.',
                'hero_description' => 'An innovative property assessment application for PT. WIKA Gedung, used for surveying residential units at Puncak CBD Apartments.',
                'summary_title'    => 'Learning About QPS WIKA Gedung',
                'image'            => 'projects/proyek_all_wika.png',
                'images'           => ['projects/proyek_all_wika.png'],
            ],
            [
                'name'             => 'SILY - Lamongan Smart City',
                'slug'             => 'sily-lamongan-smart-city',
                'category'         => 'software-development',
                'description'      => 'Unveiling the Lamongan District\'s Smart City Portal App. Explore 360-degree photos, report issues, and ensure swift emergency responses.',
                'hero_description' => 'The Lamongan District Smart City Portal App featuring 360-degree photo exploration, issue reporting, and emergency response capabilities.',
                'summary_title'    => 'Learning About SILY',
                'image'            => 'projects/proyek_softdev_silly.png',
                'images'           => ['projects/proyek_softdev_silly.png'],
            ],
            [
                'name'             => 'SIPINTAR',
                'slug'             => 'sipintar',
                'category'         => 'software-development',
                'description'      => 'Application used by the Public Works and Housing Department of Banjarbaru City to search for information on spatial planning.',
                'hero_description' => 'A spatial planning information system for the Public Works and Housing Department of Banjarbaru City.',
                'summary_title'    => 'Learning About SIPINTAR',
                'image'            => 'projects/proyek_softdev_banjarbaru.png',
                'images'           => ['projects/proyek_softdev_banjarbaru.png'],
            ],
            [
                'name'             => 'TOWER IN YOUR HAND',
                'slug'             => 'tower-in-your-hand',
                'category'         => 'software-development',
                'description'      => 'Application for supervision of telecommunication towers in Pamekasan Regency by the Department of Communication and Information Technology.',
                'hero_description' => 'A telecommunication tower supervision application for Pamekasan Regency\'s Department of Communication and Information Technology.',
                'summary_title'    => 'Learning About Tower In Your Hand',
                'image'            => 'projects/proyek_all_pamekasan.png',
                'images'           => ['projects/proyek_all_pamekasan.png'],
            ],

            // ── IT Consultant ────────────────────────────────────────────────

            [
                'name'             => 'Telkom Indonesia',
                'slug'             => 'telkom-indonesia',
                'category'         => 'it-consultant',
                'description'      => 'IT consulting and solutions for Indonesia\'s largest telecom provider.',
                'hero_description' => 'Strategic IT consulting engagement with Telkom Indonesia, providing technology solutions and digital transformation advisory services.',
                'summary_title'    => 'Learning About Telkom Indonesia',
                'image'            => 'projects/proyek_all_telkom.png',
                'images'           => ['projects/proyek_all_telkom.png'],
            ],
            [
                'name'             => 'Analisa Pengembangan dan Kebutuhan KOPERASI KANA',
                'slug'             => 'analisa-koperasi-kana',
                'category'         => 'it-consultant',
                'description'      => 'Analysis and development of application systems involving planning, design, and development to meet user needs of KOPERASI KANA.',
                'hero_description' => 'Analysis and development of application systems for KOPERASI KANA.',
                'summary_title'    => 'Learning About Analisa KOPERASI KANA',
                'image'            => 'projects/proyek_all_kana.jpg',
                'images'           => ['projects/proyek_all_kana.jpg'],
            ],
            [
                'name'             => 'Perencanaan Sistem Monitoring Ternak',
                'slug'             => 'sistem-monitoring-ternak',
                'category'         => 'it-consultant',
                'description'      => 'Technology for real-time livestock condition monitoring in collaboration with Telkom Indonesia for the Lamongan district government.',
                'hero_description' => 'Real-time livestock monitoring technology for the Lamongan district government.',
                'summary_title'    => 'Learning About Sistem Monitoring Ternak',
                'image'            => null,
                'images'           => null,
            ],
            [
                'name'             => 'Perencanaan Pengembangan Sistem PPDB',
                'slug'             => 'sistem-ppdb',
                'category'         => 'it-consultant',
                'description'      => 'Online platform for managing student admissions, including registration, data verification, selection, and announcement of results.',
                'hero_description' => 'An online platform for managing student admissions processes.',
                'summary_title'    => 'Learning About Sistem PPDB',
                'image'            => 'projects/proyek_all_ppdb.jpg',
                'images'           => ['projects/proyek_all_ppdb.jpg'],
            ],
            [
                'name'             => 'Analisa Pengembangan Koperasi BMT MUDA',
                'slug'             => 'analisa-koperasi-bmt-muda',
                'category'         => 'it-consultant',
                'description'      => 'Analysis and development of application systems involving planning and design to meet the user needs of KOPERASI BMT MUDA.',
                'hero_description' => 'Analysis and development of application systems for KOPERASI BMT MUDA.',
                'summary_title'    => 'Learning About Analisa Koperasi BMT MUDA',
                'image'            => 'projects/proyek_all_bmt.jpg',
                'images'           => ['projects/proyek_all_bmt.jpg'],
            ],
            [
                'name'             => 'POC dan Perencanaan Sistem Job Center Berau Coal',
                'slug'             => 'poc-job-center-berau-coal',
                'category'         => 'it-consultant',
                'description'      => 'Development of a prototype (POC) to prove that the design concept for the job center application can be carried out and implemented.',
                'hero_description' => 'A proof of concept for Berau Coal\'s job center application system.',
                'summary_title'    => 'Learning About POC Job Center Berau Coal',
                'image'            => 'projects/proyek_all_beraucoal.jpg',
                'images'           => ['projects/proyek_all_beraucoal.jpg'],
            ],
            [
                'name'             => 'Perencanaan Sistem Pemetaan Bangunan',
                'slug'             => 'sistem-pemetaan-bangunan',
                'category'         => 'it-consultant',
                'description'      => 'Technology implementation planning for building mapping using digital imagery, in collaboration with Telkom Indonesia for the Lamongan district government.',
                'hero_description' => 'Building mapping technology using digital imagery for the Lamongan district government.',
                'summary_title'    => 'Learning About Sistem Pemetaan Bangunan',
                'image'            => 'projects/proyek_consult_telkom.png',
                'images'           => ['projects/proyek_consult_telkom.png'],
            ],

            // ── Digital Branding ─────────────────────────────────────────────

            [
                'name'             => 'KANA Branding',
                'slug'             => 'kana-branding',
                'category'         => 'digital-branding',
                'description'      => 'Complete digital branding solution for fashion retail.',
                'hero_description' => 'A complete digital branding transformation for KANA fashion retail, creating a cohesive brand identity across all digital touchpoints.',
                'summary_title'    => 'Learning About KANA Branding',
                'image'            => 'projects/proyek_all_kana.jpg',
                'images'           => ['projects/proyek_all_kana.jpg'],
            ],
            [
                'name'             => 'Promotion Video Teknik Manufaktur Universitas Surabaya',
                'slug'             => 'promotion-video-ubaya',
                'category'         => 'digital-branding',
                'description'      => 'The promotional video showcases the Manufacturing Engineering program at the University of Surabaya, highlighting its unique features and offerings.',
                'hero_description' => 'A promotional video showcasing the Manufacturing Engineering program at the University of Surabaya.',
                'summary_title'    => 'Learning About Promotion Video UBAYA',
                'image'            => 'projects/proyek_digital_ubaya.png',
                'images'           => ['projects/proyek_digital_ubaya.png'],
            ],
            [
                'name'             => 'Rebranding Digital Marketing Queen Aisya Salon and SPA',
                'slug'             => 'rebranding-queen-aisya',
                'category'         => 'digital-branding',
                'description'      => 'Revitalizing the digital marketing strategy for Queen Aisya Salon and SPA through a comprehensive rebranding initiative.',
                'hero_description' => 'A comprehensive digital rebranding initiative for Queen Aisya Salon and SPA.',
                'summary_title'    => 'Learning About Queen Aisya Rebranding',
                'image'            => 'projects/proyek_digital_aisya.png',
                'images'           => ['projects/proyek_digital_aisya.png'],
            ],
            [
                'name'             => 'Aerial Video Company Profile PT JMF',
                'slug'             => 'aerial-video-pt-jmf',
                'category'         => 'digital-branding',
                'description'      => 'Crafting an engaging aerial company profile video for PT JMF, showcasing their expertise and services from a captivating perspective.',
                'hero_description' => 'An engaging aerial company profile video for PT Java Mining Fertilizo.',
                'summary_title'    => 'Learning About Aerial Video PT JMF',
                'image'            => 'projects/proyek_digital_jmf.png',
                'images'           => ['projects/proyek_digital_jmf.png'],
            ],

            // ── Startup Incubator ────────────────────────────────────────────

            [
                'name'             => 'Zelltech Platform',
                'slug'             => 'zelltech-platform',
                'category'         => 'startup-incubator',
                'description'      => 'Startup incubation for industrial IoT platform.',
                'hero_description' => 'Startup incubation and development support for Zelltech, an innovative industrial IoT platform connecting manufacturing operations.',
                'summary_title'    => 'Learning About Zelltech Platform',
                'image'            => 'projects/proyek_all_zelltech.png',
                'images'           => ['projects/proyek_all_zelltech.png'],
            ],
            [
                'name'             => 'Sistem Informasi Manajemen Rumah Sakit - MEDIFY',
                'slug'             => 'medify',
                'category'         => 'startup-incubator',
                'description'      => 'Digital startup incubation guiding startups focused on hospital management systems, covering investment and managed services.',
                'hero_description' => 'A digital startup incubation project for hospital management information systems.',
                'summary_title'    => 'Learning About MEDIFY',
                'image'            => null,
                'images'           => null,
            ],
            [
                'name'             => 'Sistem Ruang Komunitas - RUANGTEMU',
                'slug'             => 'ruangtemu',
                'category'         => 'startup-incubator',
                'description'      => 'Digital-based startup incubation providing community event news and event management, focused on Tech Investment and Tech Consultants.',
                'hero_description' => 'A community event platform providing news and event management capabilities.',
                'summary_title'    => 'Learning About RUANGTEMU',
                'image'            => null,
                'images'           => null,
            ],
            [
                'name'             => 'Sistem Aplikasi Kontraktor',
                'slug'             => 'sistem-aplikasi-kontraktor',
                'category'         => 'startup-incubator',
                'description'      => 'Digital-based startup incubation providing a project monitoring application for construction contractors, covering Tech Consultant and Managed Services.',
                'hero_description' => 'A project monitoring application for construction contractors.',
                'summary_title'    => 'Learning About Sistem Aplikasi Kontraktor',
                'image'            => 'projects/proyek_startup_kontraktor.jpg',
                'images'           => ['projects/proyek_startup_kontraktor.jpg'],
            ],
            [
                'name'             => 'Sistem Aplikasi Manufaktur Industri',
                'slug'             => 'sistem-aplikasi-manufaktur',
                'category'         => 'startup-incubator',
                'description'      => 'Digital-based startup incubation providing manufacturing application systems for industry, covering Tech Consultant and Managed Services.',
                'hero_description' => 'Manufacturing application systems for industrial operations.',
                'summary_title'    => 'Learning About Sistem Aplikasi Manufaktur Industri',
                'image'            => 'projects/proyek_all_industri.jpg',
                'images'           => ['projects/proyek_all_industri.jpg'],
            ],
            [
                'name'             => 'Sistem Koperasi CALCIUS',
                'slug'             => 'sistem-koperasi-calcius',
                'category'         => 'startup-incubator',
                'description'      => 'Digital-based startup incubation providing cooperative organization information systems, covering Tech Investment and Business Consultant.',
                'hero_description' => 'A cooperative organization information system for CALCIUS.',
                'summary_title'    => 'Learning About Sistem Koperasi CALCIUS',
                'image'            => 'projects/proyek_all_calcius.jpg',
                'images'           => ['projects/proyek_all_calcius.jpg'],
            ],

        ];

        foreach ($projects as $data) {
            Project::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
