<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'name' => 'Berau Coal ERP',
                'slug' => 'berau-coal-erp',
                'category' => 'software-development',
                'description' => 'Enterprise Resource Planning system for coal mining operations.',
                'hero_description' => 'A comprehensive ERP system designed to manage all aspects of coal mining operations, from resource tracking to logistics and financial management.',
                'summary_title' => 'Learning About Berau Coal ERP',
                'image' => 'proyek_all_beraucoal.jpg',
                'content' => '<p>Berau Coal ERP is a comprehensive enterprise resource planning system developed to streamline coal mining operations. The platform integrates multiple business processes including resource tracking, logistics management, financial reporting, and workforce coordination.</p><h3>Key Features</h3><ul><li>Real-time resource tracking and monitoring</li><li>Integrated logistics and supply chain management</li><li>Financial reporting and analytics dashboard</li><li>Workforce scheduling and management</li></ul>',
                'images' => ['proyek_all_beraucoal.jpg'],
            ],
            [
                'name' => 'BMT Muda',
                'slug' => 'bmt-muda',
                'category' => 'software-development',
                'description' => 'Digital financial platform for microfinance institution.',
                'hero_description' => 'A modern digital financial platform built for BMT Muda, enabling efficient microfinance operations and empowering community-based financial services.',
                'summary_title' => 'Learning About BMT Muda',
                'image' => 'proyek_all_bmt.jpg',
                'content' => '<p>BMT Muda is a digital transformation project for a microfinance institution, featuring loan management, member tracking, and financial reporting capabilities.</p><h3>Key Features</h3><ul><li>Member management system</li><li>Loan processing and tracking</li><li>Financial reporting dashboard</li><li>Mobile-friendly interface</li></ul>',
                'images' => ['proyek_all_bmt.jpg'],
            ],
            [
                'name' => 'Telkom Indonesia',
                'slug' => 'telkom-indonesia',
                'category' => 'it-consultant',
                'description' => 'IT consulting and solutions for Indonesia\'s largest telecom provider.',
                'hero_description' => 'Strategic IT consulting engagement with Telkom Indonesia, providing technology solutions and digital transformation advisory services.',
                'summary_title' => 'Learning About Telkom Indonesia',
                'image' => 'proyek_all_telkom.svg',
                'content' => '<p>Our consulting engagement with Telkom Indonesia involved strategic technology advisory, system optimization, and digital transformation initiatives for Indonesia\'s largest telecommunications provider.</p>',
                'images' => ['proyek_all_telkom.svg'],
            ],
            [
                'name' => 'WIKA Construction',
                'slug' => 'wika-construction',
                'category' => 'software-development',
                'description' => 'Digital transformation project for state-owned construction company.',
                'hero_description' => 'A digital transformation initiative for WIKA, one of Indonesia\'s largest state-owned construction companies, modernizing project management and operations.',
                'summary_title' => 'Learning About WIKA Construction',
                'image' => 'proyek_all_wika.svg',
                'content' => '<p>WIKA Construction digital transformation project modernized the project management workflows, resource allocation, and reporting systems for one of Indonesia\'s premier construction companies.</p>',
                'images' => ['proyek_all_wika.svg'],
            ],
            [
                'name' => 'Unilever Analytics',
                'slug' => 'unilever-analytics',
                'category' => 'software-development',
                'description' => 'Business intelligence and analytics platform for FMCG operations.',
                'hero_description' => 'Advanced business intelligence and analytics platform developed for Unilever, enabling data-driven decision making across FMCG operations.',
                'summary_title' => 'Learning About Unilever Analytics',
                'image' => 'proyek_all_unilever.svg',
                'content' => '<p>A comprehensive analytics platform built for Unilever\'s FMCG operations, providing real-time insights into sales performance, market trends, and supply chain optimization.</p>',
                'images' => ['proyek_all_unilever.svg'],
            ],
            [
                'name' => 'KANA Branding',
                'slug' => 'kana-branding',
                'category' => 'digital-branding',
                'description' => 'Complete digital branding solution for fashion retail.',
                'hero_description' => 'A complete digital branding transformation for KANA fashion retail, creating a cohesive brand identity across all digital touchpoints.',
                'summary_title' => 'Learning About KANA Branding',
                'image' => 'proyek_all_kana.jpg',
                'content' => '<p>KANA Branding project delivered a comprehensive digital identity system for a fashion retail brand, including logo design, visual guidelines, social media presence, and e-commerce platform branding.</p>',
                'images' => ['proyek_all_kana.jpg'],
            ],
            [
                'name' => 'Zelltech Platform',
                'slug' => 'zelltech-platform',
                'category' => 'startup-incubator',
                'description' => 'Startup incubation for industrial IoT platform.',
                'hero_description' => 'Startup incubation and development support for Zelltech, an innovative industrial IoT platform connecting manufacturing operations.',
                'summary_title' => 'Learning About Zelltech Platform',
                'image' => 'proyek_all_zelltech.svg',
                'content' => '<p>Zelltech Platform is an industrial IoT startup that we incubated from concept to market-ready product, providing technical architecture, development support, and go-to-market strategy.</p>',
                'images' => ['proyek_all_zelltech.svg'],
            ],
            [
                'name' => 'Pamekasan Smart City',
                'slug' => 'pamekasan-smart-city',
                'category' => 'software-development',
                'description' => 'Smart city application for Kabupaten Pamekasan.',
                'hero_description' => 'A smart city application developed for Kabupaten Pamekasan, integrating public services, data analytics, and citizen engagement into a unified digital platform.',
                'summary_title' => 'Learning About Pamekasan Smart City',
                'image' => 'proyek_all_pamekasan.svg',
                'content' => '<p>Pamekasan Smart City is an integrated digital platform for city governance, public service delivery, and citizen engagement developed for the Pamekasan regency.</p>',
                'images' => ['proyek_all_pamekasan.svg'],
            ],
            [
                'name' => 'INDIPRO TELKOM SURABAYA',
                'slug' => 'indipro-telkom-surabaya',
                'category' => 'software-development',
                'description' => 'Effortless online booking experience for home internet installation, enriched with advanced GIS features.',
                'hero_description' => 'An online booking platform for Telkom Surabaya, enabling seamless home internet installation scheduling with advanced GIS-based coverage mapping.',
                'summary_title' => 'Learning About INDIPRO Telkom Surabaya',
                'image' => 'proyek_all_telkom.svg',
                'content' => '<p>INDIPRO is an innovative platform developed for Telkom Surabaya that simplifies home internet installation booking with GIS-powered features.</p>',
                'images' => ['proyek_all_telkom.svg'],
            ],
            [
                'name' => 'E-SALES ZELLTECH',
                'slug' => 'e-sales-zelltech',
                'category' => 'software-development',
                'description' => 'Zelltech\'s application: A powerful tool for PT Celcius Indo Perkasa, enabling seamless sales tracking and project monitoring.',
                'hero_description' => 'A powerful sales tracking and project monitoring application developed for Zelltech / PT Celcius Indo Perkasa.',
                'summary_title' => 'Learning About E-Sales Zelltech',
                'image' => 'proyek_all_zelltech.svg',
                'content' => '<p>E-Sales Zelltech is a comprehensive sales management platform for tracking and monitoring sales activities and project progress.</p>',
                'images' => ['proyek_all_zelltech.svg'],
            ],
            [
                'name' => 'SISTEM WAREHOUSE - MJS UNILEVER',
                'slug' => 'sistem-warehouse-mjs-unilever',
                'category' => 'software-development',
                'description' => 'Efficient system facilitating inventory tracking for MJA Company, a trusted Unilever distributor.',
                'hero_description' => 'A warehouse management system built for MJA Company, a trusted Unilever distributor, to streamline inventory tracking and distribution.',
                'summary_title' => 'Learning About Sistem Warehouse MJS Unilever',
                'image' => 'proyek_all_unilever.svg',
                'content' => '<p>An efficient warehouse management system facilitating inventory tracking operations for MJA Company, a key Unilever distributor.</p>',
                'images' => ['proyek_all_unilever.svg'],
            ],
            [
                'name' => 'QPS WIKA GEDUNG',
                'slug' => 'qps-wika-gedung',
                'category' => 'software-development',
                'description' => 'Revolutionizing property assessments, PT. WIKA Gedung employs an innovative application for surveying residential units at Puncak CBD Apartments.',
                'hero_description' => 'An innovative property assessment application for PT. WIKA Gedung, used for surveying residential units at Puncak CBD Apartments.',
                'summary_title' => 'Learning About QPS WIKA Gedung',
                'image' => 'proyek_all_wika.svg',
                'content' => '<p>QPS WIKA Gedung is an innovative application that revolutionizes property assessments for surveying residential units.</p>',
                'images' => ['proyek_all_wika.svg'],
            ],
            [
                'name' => 'SILY - Lamongan Smart City',
                'slug' => 'sily-lamongan-smart-city',
                'category' => 'software-development',
                'description' => 'Unveiling the Lamongan District\'s Smart City Portal App. Explore 360-degree photos, report issues, and ensure swift emergency responses.',
                'hero_description' => 'The Lamongan District Smart City Portal App featuring 360-degree photo exploration, issue reporting, and emergency response capabilities.',
                'summary_title' => 'Learning About SILY',
                'image' => 'proyek_softdev_silly.svg',
                'content' => '<p>SILY is the Lamongan District Smart City Portal application providing 360-degree exploration, issue reporting, and emergency response features.</p>',
                'images' => ['proyek_softdev_silly.svg'],
            ],
            [
                'name' => 'SIPINTAR',
                'slug' => 'sipintar',
                'category' => 'software-development',
                'description' => 'Application used by the Public Works and Housing Department of Banjarbaru City to search for information on spatial planning.',
                'hero_description' => 'A spatial planning information system for the Public Works and Housing Department of Banjarbaru City.',
                'summary_title' => 'Learning About SIPINTAR',
                'image' => 'proyek_softdev_banjarbaru.svg',
                'content' => '<p>SIPINTAR assists the Public Works and Housing Department of Banjarbaru City in spatial planning information management.</p>',
                'images' => ['proyek_softdev_banjarbaru.svg'],
            ],
            [
                'name' => 'TOWER IN YOUR HAND',
                'slug' => 'tower-in-your-hand',
                'category' => 'software-development',
                'description' => 'Application for supervision of telecommunication towers in Pamekasan Regency by the Department of Communication and Information Technology.',
                'hero_description' => 'A telecommunication tower supervision application for Pamekasan Regency\'s Department of Communication and Information Technology.',
                'summary_title' => 'Learning About Tower In Your Hand',
                'image' => 'proyek_all_pamekasan.svg',
                'content' => '<p>Tower In Your Hand enables supervision of all telecommunication towers across Pamekasan Regency.</p>',
                'images' => ['proyek_all_pamekasan.svg'],
            ],
            [
                'name' => 'Promotion Video Teknik Manufaktur Universitas Surabaya',
                'slug' => 'promotion-video-ubaya',
                'category' => 'digital-branding',
                'description' => 'The promotional video showcases the Manufacturing Engineering program at the University of Surabaya, highlighting its unique features and offerings.',
                'hero_description' => 'A promotional video showcasing the Manufacturing Engineering program at the University of Surabaya.',
                'summary_title' => 'Learning About Promotion Video UBAYA',
                'image' => 'proyek_digital_ubaya.svg',
                'content' => '<p>A promotional video created for the Manufacturing Engineering program at the University of Surabaya, highlighting its unique features and academic offerings.</p>',
                'images' => ['proyek_digital_ubaya.svg'],
            ],
            [
                'name' => 'Rebranding Digital Marketing Queen Aisya Salon and SPA',
                'slug' => 'rebranding-queen-aisya',
                'category' => 'digital-branding',
                'description' => 'Revitalizing the digital marketing strategy for Queen Aisya Salon and SPA through a comprehensive rebranding initiative.',
                'hero_description' => 'A comprehensive digital rebranding initiative for Queen Aisya Salon and SPA.',
                'summary_title' => 'Learning About Queen Aisya Rebranding',
                'image' => 'proyek_digital_aisya.svg',
                'content' => '<p>Revitalizing the digital marketing strategy for Queen Aisya Salon and SPA through a comprehensive rebranding initiative covering social media, visual identity, and online presence.</p>',
                'images' => ['proyek_digital_aisya.svg'],
            ],
            [
                'name' => 'Aerial Video Company Profile PT JMF',
                'slug' => 'aerial-video-pt-jmf',
                'category' => 'digital-branding',
                'description' => 'Crafting an engaging aerial company profile video for PT JMF, showcasing their expertise and services from a captivating perspective.',
                'hero_description' => 'An engaging aerial company profile video for PT Java Mining Fertilizo.',
                'summary_title' => 'Learning About Aerial Video PT JMF',
                'image' => 'proyek_digital_jmf.png',
                'content' => '<p>Crafting an engaging aerial company profile video for PT JMF, showcasing their expertise and services from a captivating aerial perspective.</p>',
                'images' => ['proyek_digital_jmf.png'],
            ],
            [
                'name' => 'Sistem Informasi Manajemen Rumah Sakit - MEDIFY',
                'slug' => 'medify',
                'category' => 'startup-incubator',
                'description' => 'Digital startup incubation guiding startups focused on hospital management systems, covering investment and managed services.',
                'hero_description' => 'A digital startup incubation project for hospital management information systems.',
                'summary_title' => 'Learning About MEDIFY',
                'image' => null,
                'content' => '<p>MEDIFY is a hospital management information system developed through digital startup incubation, covering investment strategy and managed services.</p>',
                'images' => null,
            ],
            [
                'name' => 'Sistem Ruang Komunitas - RUANGTEMU',
                'slug' => 'ruangtemu',
                'category' => 'startup-incubator',
                'description' => 'Digital-based startup incubation providing community event news and event management, focused on Tech Investment and Tech Consultants.',
                'hero_description' => 'A community event platform providing news and event management capabilities.',
                'summary_title' => 'Learning About RUANGTEMU',
                'image' => null,
                'content' => '<p>RUANGTEMU is a community event platform developed through startup incubation, providing event news, management, and community engagement features.</p>',
                'images' => null,
            ],
            [
                'name' => 'Sistem Aplikasi Kontraktor',
                'slug' => 'sistem-aplikasi-kontraktor',
                'category' => 'startup-incubator',
                'description' => 'Digital-based startup incubation providing a project monitoring application for construction contractors, covering Tech Consultant and Managed Services.',
                'hero_description' => 'A project monitoring application for construction contractors.',
                'summary_title' => 'Learning About Sistem Aplikasi Kontraktor',
                'image' => 'proyek_startup_kontraktor.jpg',
                'content' => '<p>A project monitoring application for construction contractors developed through startup incubation program.</p>',
                'images' => ['proyek_startup_kontraktor.jpg'],
            ],
            [
                'name' => 'Sistem Aplikasi Manufaktur Industri',
                'slug' => 'sistem-aplikasi-manufaktur',
                'category' => 'startup-incubator',
                'description' => 'Digital-based startup incubation providing manufacturing application systems for industry, covering Tech Consultant and Managed Services.',
                'hero_description' => 'Manufacturing application systems for industrial operations.',
                'summary_title' => 'Learning About Sistem Aplikasi Manufaktur Industri',
                'image' => 'proyek_all_industri.jpg',
                'content' => '<p>A manufacturing application system for industry developed through startup incubation program.</p>',
                'images' => ['proyek_all_industri.jpg'],
            ],
            [
                'name' => 'Sistem Koperasi CALCIUS',
                'slug' => 'sistem-koperasi-calcius',
                'category' => 'startup-incubator',
                'description' => 'Digital-based startup incubation providing cooperative organization information systems, covering Tech Investment and Business Consultant.',
                'hero_description' => 'A cooperative organization information system for CALCIUS.',
                'summary_title' => 'Learning About Sistem Koperasi CALCIUS',
                'image' => 'proyek_all_calcius.jpg',
                'content' => '<p>A cooperative organization information system developed for CALCIUS through startup incubation program.</p>',
                'images' => ['proyek_all_calcius.jpg'],
            ],
            [
                'name' => 'Analisa Pengembangan dan Kebutuhan KOPERASI KANA',
                'slug' => 'analisa-koperasi-kana',
                'category' => 'it-consultant',
                'description' => 'Analysis and development of application systems involving planning, design, and development to meet user needs of KOPERASI KANA.',
                'hero_description' => 'Analysis and development of application systems for KOPERASI KANA.',
                'summary_title' => 'Learning About Analisa KOPERASI KANA',
                'image' => 'proyek_all_kana.jpg',
                'content' => '<p>Analysis and development of application systems involving planning, design, and development to meet user needs of KOPERASI KANA.</p>',
                'images' => ['proyek_all_kana.jpg'],
            ],
            [
                'name' => 'Perencanaan Sistem Monitoring Ternak',
                'slug' => 'sistem-monitoring-ternak',
                'category' => 'it-consultant',
                'description' => 'Technology for real-time livestock condition monitoring in collaboration with Telkom Indonesia for the Lamongan district government.',
                'hero_description' => 'Real-time livestock monitoring technology for the Lamongan district government.',
                'summary_title' => 'Learning About Sistem Monitoring Ternak',
                'image' => null,
                'content' => '<p>Technology implementation for real-time livestock condition monitoring in collaboration with Telkom Indonesia for the Lamongan district government.</p>',
                'images' => null,
            ],
            [
                'name' => 'Perencanaan Pengembangan Sistem PPDB',
                'slug' => 'sistem-ppdb',
                'category' => 'it-consultant',
                'description' => 'Online platform for managing student admissions, including registration, data verification, selection, and announcement of results.',
                'hero_description' => 'An online platform for managing student admissions processes.',
                'summary_title' => 'Learning About Sistem PPDB',
                'image' => 'proyek_all_ppdb.jpg',
                'content' => '<p>An online platform for managing student admissions, including registration, data verification, selection, and announcement of results.</p>',
                'images' => ['proyek_all_ppdb.jpg'],
            ],
            [
                'name' => 'Analisa Pengembangan Koperasi BMT MUDA',
                'slug' => 'analisa-koperasi-bmt-muda',
                'category' => 'it-consultant',
                'description' => 'Analysis and development of application systems involving planning and design to meet the user needs of KOPERASI BMT MUDA.',
                'hero_description' => 'Analysis and development of application systems for KOPERASI BMT MUDA.',
                'summary_title' => 'Learning About Analisa Koperasi BMT MUDA',
                'image' => 'proyek_all_bmt.jpg',
                'content' => '<p>Analysis and development of application systems involving planning and design to meet the user needs of KOPERASI BMT MUDA.</p>',
                'images' => ['proyek_all_bmt.jpg'],
            ],
            [
                'name' => 'POC dan Perencanaan Sistem Job Center Berau Coal',
                'slug' => 'poc-job-center-berau-coal',
                'category' => 'it-consultant',
                'description' => 'Development of a prototype (POC) to prove that the design concept for the job center application can be carried out and implemented.',
                'hero_description' => 'A proof of concept for Berau Coal\'s job center application system.',
                'summary_title' => 'Learning About POC Job Center Berau Coal',
                'image' => 'proyek_all_beraucoal.jpg',
                'content' => '<p>Development of a prototype (POC) to prove that the design concept for the job center application can be carried out and implemented for Berau Coal.</p>',
                'images' => ['proyek_all_beraucoal.jpg'],
            ],
            [
                'name' => 'Perencanaan Sistem Pemetaan Bangunan',
                'slug' => 'sistem-pemetaan-bangunan',
                'category' => 'it-consultant',
                'description' => 'Technology implementation planning for building mapping using digital imagery, in collaboration with Telkom Indonesia for the Lamongan district government.',
                'hero_description' => 'Building mapping technology using digital imagery for the Lamongan district government.',
                'summary_title' => 'Learning About Sistem Pemetaan Bangunan',
                'image' => 'proyek_consult_telkom.png',
                'content' => '<p>Technology implementation planning for building mapping using digital imagery, in collaboration with Telkom Indonesia for the Lamongan district government.</p>',
                'images' => ['proyek_consult_telkom.png'],
            ],
        ];

        foreach ($projects as $project) {
            if (isset($project['content'])) {
                $project['description'] = $project['content'];
            }
            Project::create($project);
        }
    }
}
